[package]
name = "advent-of-code"
version = "0.1.0"
authors = ["tsanthosh <santosht@thoughtworks.com>"]
edition = "2018"
include = ["data/*.data"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]